// Generated by CoffeeScript 1.12.7
(function() {
  var dao, git_handler, main, member_handler, tasks_handler, vault;

  main = artifacts.require('Main');

  dao = artifacts.require('Dao');

  member_handler = artifacts.require('MemberHandler');

  vault = artifacts.require('Vault');

  tasks_handler = artifacts.require('TasksHandler');

  git_handler = artifacts.require('GitHandler');

  module.exports = (function(_this) {
    return function(deployer) {
      return deployer.deploy(main, 'Test Metadata').then(function() {
        return deployer.deploy([[dao, main.address], [member_handler, 'Test Username', main.address], [vault, main.address], [tasks_handler, main.address], [git_handler, main.address]]).then(function() {
          return main.deployed().then(function(instance) {
            return instance.initializeModuleAddresses([dao.address, member_handler.address, vault.address, tasks_handler.address, git_handler.address]);
          });
        }).then(function() {
          return dao.deployed().then(function(instance) {
            return instance.init();
          });
        });
      });
    };
  })(this);

}).call(this);

//# sourceMappingURL=2_core_contracts.js.map
