// Generated by CoffeeScript 1.12.6
(function() {
  var Dao, MemberHandler, daoAddr, memAddr;

  Dao = artifacts.require('Dao');

  MemberHandler = artifacts.require('MemberHandler');

  daoAddr = '0xbcfc50e23f9938a6376083dbb9392271dcca45af';

  memAddr = '0x7b657f1a84693d70fea10d99a290c873fdbe5b5d';

  contract('Dao', function(accounts) {
    var account1, account2;
    account1 = accounts[0];
    account2 = accounts[1];
    it('create voting', function() {
      return Dao.at(daoAddr).then(function(instance) {
        return instance.createVoting('Test Voting', 'For testing the creation of votings', 0, 100, [], "0x0");
      });
    });
    it('has right', function() {
      return MemberHandler.at(memAddr).then(function(instance) {
        return instance.memberHasRight(account1, 'vote');
      });
    });
    it('vote on voting', function() {
      return Dao.at(daoAddr).then(function(instance) {
        return instance.vote(5, true);
      });
    });
  });

}).call(this);

//# sourceMappingURL=voting.js.map
