// Generated by CoffeeScript 1.12.7
(function() {
  var Dao;

  Dao = artifacts.require('Dao');

  contract('Dao', (function(_this) {
    return function(accounts) {
      return it('create voting', function() {
        return Dao.deployed().then(function(instance) {
          return instance.createVoting('Test Voting', 'For testing the creation of votings', 0, 0, [], "0x0");
        });
      });
    };
  })(this));

}).call(this);

//# sourceMappingURL=voting.js.map
