// Generated by CoffeeScript 1.12.7
(function() {
  var Dao;

  Dao = artifacts.require('Dao');

  contract('Dao', (function(_this) {
    return function(accounts) {
      var account1, account2;
      account1 = accounts[0];
      account2 = accounts[1];
      it('create voting', function() {
        return Dao.deployed().then(function(instance) {
          return instance.createVoting('Test Voting', 'For testing the creation of votings', 0, 0, [], "0x0");
        });
      });
      return it('vote on voting', function() {
        return Dao.deployed().then(function(instance) {
          return instance.vote(0, true);
        });
      });
    };
  })(this));

}).call(this);

//# sourceMappingURL=voting.js.map
